### ISSUE TITLE
Option to only show symbol in the header bar

### ISSUE THREAD

**Issue by fiagewinnt** [Kekilla0/Item-Macro#11]
I wanted to ask if it would be possible to add an option to only show the symbol in the header bar and not also the text to preserve space? Since I'm running Foundry with a lot of modules that also use the header bar, it got kinda overcrowded now and doesn't show the close button anymore. Only when I resize each window manually every time I open a spell/journal entry etc. to accomodate all the symbols. 

Before resizing:
![image](https://user-images.githubusercontent.com/61601634/111866763-17964a80-8970-11eb-92bd-abf88549cde7.png)

After resizing:
![image](https://user-images.githubusercontent.com/61601634/111866774-27ae2a00-8970-11eb-8aae-29e40b42c632.png)

**Comment by Kekilla0** [comment]
This setting will be added in the new version.

**Comment by Kekilla0** [comment]
This option has been added to the latest version!
