### ISSUE TITLE
Running item effect and item macro at the same time. 

### ISSUE THREAD

**Issue by grendel111111** [Kekilla0/Item-Macro#14]
I am using SWADE and I have a power (bolt) it has an electric graphic effect from token magic FX and JB2, in the macro. I am wanting to fire the macro and the power at the same time. All examples of this seem to need the DAE or Midi QOL to work, but I don't have access to either of these modules (As it isn't a D20 system) Is there a way to launch the macro when you use the normal effect of the spell (rolling dice, etc)?

**Comment by Kekilla0** [comment]
This isn't really an "issue".

But, when you have item macro execute things, it only executes the macro as you give it. So with this --- you do not need DAE or MIDI to make ANYTHING work. You just write the macro you want as you want it to execute. DAE and MIDI just make the automation more streamlined for 5e players.
