### ISSUE TITLE
No more manifest for releases prior to 0.8

### ISSUE THREAD

**Issue by warteckel** [Kekilla0/Item-Macro#16]
No more manifest URL are provided for people who are still using 0.7.X version of the foundry. All the provided URL manifests published are linked to the 1.5.2 version which needs a 0.8.X version of the foundry.

**Comment by DHubbert** [comment]
Any particular reason for that? 0.8.X is still in beta most people probably aren't using it?

**Comment by Kekilla0** [comment]
the issue is im lazy and don't quite know how manifests work

so instead of constantly messing up with new manifests, item-macros just points to the newest version. 

if you need pre 0.8.X, you can manually install it. Yes in newer versions I will attempt to figure out what i am doing.

**Comment by Kekilla0** [comment]
Fixing this with the newest release (0.7.X will not be reupdated) If you are still having issues install using : 
https://github.com/Kekilla0/Item-Macro/archive/refs/tags/v1.5.1.zip

will need to be unpacked and placed in the right folders.

**Comment by DHubbert** [comment]
Thanks - I'll just use that older version for now.
