### ISSUE TITLE
error on actor hook setting

### ISSUE THREAD

**Issue by SR5060** [Kekilla0/Item-Macro#19]
following error is thrown when setting the character sheet hook setting. I believe this is also causing that setting to not work. foundry 0.8.7

![image](https://user-images.githubusercontent.com/85184490/122792303-a96b6780-d27f-11eb-82e8-d8d83ee257ea.png)

**Comment by Kekilla0** [comment]
need more information than this, with only item-macro enabled the module seems to work fine on 0.8.7

**Comment by SR5060** [comment]
So I used find the culprit to only test it with item macro and it still threw the error (occurs when enabling or disabling the setting and clicking save changes). on dhd 5e 1.3.5 and 0.8.7

anything else I can provide?

**Comment by SR5060** [comment]
yea just tried it on a fresh world too and the error still occurred

**Comment by Kekilla0** [comment]
believe i found the issue, going to be pushing it soon.

**Comment by SR5060** [comment]
Glad to hear, sorry I couldn't provide more information!

**Comment by Kekilla0** [comment]
Sorry for the wait, updating now.
