### ISSUE TITLE
"Save Macro" button causes the macro to be configured as "chat", which does not properly execute.

### ISSUE THREAD

**Issue by spurrkins** [Kekilla0/Item-Macro#21]
Reproduced on a fresh world with no modules ever installed.
Foundry v0.8.8
dnd 5e v1.3.6
item-macro v1.5.4

Steps to reproduce (may be a more minimal set):
1. Create dnd5e world, create scene, create a test actor, drag actor to scene
2. Give actor an item
3. Enable item-macro with character sheet hook
4. Add macro to item, something basic like log to console, save without executing.  Try clicking the item, nothing happens. 
5. Reopen macro, click execute, close without saving
6. Item now functions totally as expected

After step 4, I added a breakpoint here https://github.com/Kekilla0/Item-Macro/blob/master/scripts/helper.js#L31
And found the chat configuration. 
![image](https://user-images.githubusercontent.com/12702538/125208245-40f02480-e246-11eb-9940-ddebf4710c84.png)

An additional breakpoint here https://github.com/Kekilla0/Item-Macro/blob/master/scripts/ItemMacroConfig.js#L51
Revealed: 
![image](https://user-images.githubusercontent.com/12702538/125208516-c58f7280-e247-11eb-947a-5f26c0cd9f90.png)

**Comment by spurrkins** [comment]
Some minor further testing revealed that the "Save Macro" button always seems to save a macro as a chat macro, and "Execute Macro" will properly save it on the item as a script.

**Comment by Kekilla0** [comment]
update from 0.8.8 must have changed how MacroConfig builds formData. Update incoming.
