### ISSUE TITLE
Item Macros don't accept arguments when called via macro

### ISSUE THREAD

**Issue by BadIdeasBureau** [Kekilla0/Item-Macro#3]
(Throwing an issue here, rather than talking on Discord about this)

I *think* this is possible with some small edits to "executeMacro()" and "runMacro()", but don't have the javascript knowledge to put this into practice. (any code in the following should be assumed to be wrong!)

In runMacro, (line 139 of itemMacro.js), change its arguments to `runMacro(_actorID, _itemID, arguments[])`

In executeMacro (line 81), change its arguments to `executeMacro(_actorID, _itemID, arguments[])`

And then change line 102 to `}).execute(arguments)`

It might need some extra stuff to unpack the arguments from the array before passing them to execute, but it should then allow any macro to call `runMacro("Actor", "Item", ["arg0", "arg1", "arg2"])` and have those arguments passed on to the item macro.

Why is this useful?  it means that for an item in a shared compendium, you can set up Dynamic Effects to call a macro with specific arguments, and then share this item between worlds without having to also share the macro.  (or in my somewhat excessive case, all I would need to share are the non-item-specific helper macros, like the one that applies damage)

**Comment by Kekilla0** [comment]
This would also require a dependancy for the Furnace. Not sure if I am 100% on board with that.

**Comment by BadIdeasBureau** [comment]
Fair enough - hadn't realised that Furnace was what added arguments to macros!  Yeah, avoiding that dependency is reasonable.  I'll just have to import both an item and a macro for each spell to make my ridiculous workflow work then :P
