### ISSUE TITLE
Support for Simple Worldbuilding

### ISSUE THREAD

**Issue by Benyblaze** [Kekilla0/Item-Macro#31]
Simple Worldbuilding is one of the core Foundry modules and, even though it is very limited, it is flexible.

Item creation on that module basically only allow short formulas to be associated with items. If the item entity could call for a macro, it would basically solve all problems for custom games.

I do not even know if that is possible, however, I hope this gets to be considered with care.

**Comment by Kekilla0** [comment]
> Simple Worldbuilding is one of the core Foundry modules and, even though it is very limited, it is flexible.
> 
> Item creation on that module basically only allow short formulas to be associated with items. If the item entity could call for a macro, it would basically solve all problems for custom games.
> 
> I do not even know if that is possible, however, I hope this gets to be considered with care.

where could i get information about the system? My preferred form of communication is discord.

**Comment by Benyblaze** [comment]
> > Simple Worldbuilding is one of the core Foundry modules and, even though it is very limited, it is flexible.
> > Item creation on that module basically only allow short formulas to be associated with items. If the item entity could call for a macro, it would basically solve all problems for custom games.
> > I do not even know if that is possible, however, I hope this gets to be considered with care.
> 
> where could i get information about the system? My preferred form of communication is discord.

Simple Worldbuilding is developed by Atropos himself it seems. So I guess you can e-mail him at [admin@foundryvtt.com](mailto:admin@foundryvtt.com) OR, since you prefer discord, try to contact him through there ( Atropos#3814 ).

**Comment by Kekilla0** [comment]
> > > Simple Worldbuilding is one of the core Foundry modules and, even though it is very limited, it is flexible.
> > > Item creation on that module basically only allow short formulas to be associated with items. If the item entity could call for a macro, it would basically solve all problems for custom games.
> > > I do not even know if that is possible, however, I hope this gets to be considered with care.
> > 
> > 
> > where could i get information about the system? My preferred form of communication is discord.
> 
> Simple Worldbuilding is developed by Atropos himself it seems. So I guess you can e-mail him at [admin@foundryvtt.com](mailto:admin@foundryvtt.com) OR, since you prefer discord, try to contact him through there ( Atropos#3814 ).

Atro isn't going to be able to tell me what the basic user of the system wants, thats where you come in. Contact me if you can on discord.

**Comment by Benyblaze** [comment]
Thank you so much for your attention, I will contact you on discord ASAP!

**Comment by trioderegion** [comment]
Added in 1.6.0
