### ISSUE TITLE
Support for SW5e

### ISSUE THREAD

**Issue by TogaParty** [Kekilla0/Item-Macro#32]
I've submitted the update to module.json (I think).  This is essentially D&D5e, but for Star Wars.

**Comment by Kekilla0** [comment]
> I've submitted the update to module.json (I think). This is essentially D&D5e, but for Star Wars.

where could i get information about the system? My preferred form of communication is discord.

**Comment by TogaParty** [comment]
I don't know which channel(s) to find you on, or your username.

Assuming you mean the system for foundry can be found here: https://github.com/unrealkakeman89/sw5e

The rules for the system live here: https://sw5e.com/

**Comment by trioderegion** [comment]
As this is an unlisted system, it is outside the scope of direct support.

However, we will accept an PR containing the changes needed to support this system.
