### ISSUE TITLE
"Token" is a tokenDocument for synthetic actors.

### ISSUE THREAD

**Issue by krbz999** [Kekilla0/Item-Macro#33]
[The code in question](https://github.com/Kekilla0/Item-Macro/blob/1b70425c49ecfc5938ca77e6d896d614f0953f2e/scripts/helper.js#L50)

An item macro executed on a linked actor has token correctly for the `token` constant, but is a token document for unlinked actors.

It would be an easy fix with `item.actor?.token?.object`.

**Comment by Kekilla0** [comment]
Will be fixed for V10
