### ISSUE TITLE
can't drag item to hotbar in Simple Worldbuilding

### ISSUE THREAD

**Issue by EsotericOdyssey** [Kekilla0/Item-Macro#38]
can't drag items from either the item directory or an actor sheet into the hotbar in the Simple Worldbuilding system. Unfortunately I don't currently have a way to easily set up a test environment with just the Item Macro module and no others enabled, so I can't confirm whether that's a problem with Item Macro or some other module.

**Comment by trioderegion** [comment]
ensure that you have the option for "override default macro execution" enabled. Creating the macro will only work (to my knowledge) when pulled from an Actor sheet (though, I didnt explicitly test from the sidebar)
