### ISSUE TITLE
Feature suggestion: Execute on Save Failed/Passed

### ISSUE THREAD

**Issue by Avera9eJoe** [Kekilla0/Item-Macro#43]
**Description:** I would love the addition of a *'After Save Failed'* and *'After Save Passed'* option in the execute macro box as there doesn't seem to be a way to only execute a macro if the item succeeds.

**Example usage:**
* I.E. create a macro to move a target 10m closer, and add it to the Gust spell with the execute option *'After Save Failed'*. Now if the target fails their save, it activates the macro and moves the target 10m closer, but only if the target fails their save.

![image](https://user-images.githubusercontent.com/5304201/185054777-2361c929-b801-46ec-934b-e6a59122cdee.png)
\+ After Save Failed
\+ After Save Passed

**Comment by trioderegion** [comment]
You might be mixing up module functionalities. This is a MIDI menu for its own macro execution, not controlled by Item Macro.
