### ISSUE TITLE
Preventing Magic Item mod firing

### ISSUE THREAD

**Issue by crymic** [Kekilla0/Item-Macro#5]
If I create a magic item and attach a spell to it. You go into the spellbook to fire the magic item.
This cannot happen when itemmacro module is enabled.

`itemMacro.js:291 Uncaught (in promise) TypeError: Cannot read property 'data' of null
    at HTMLDivElement.<anonymous> (itemMacro.js:291)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.v.handle (jquery.min.js:2)`

**Comment by Kekilla0** [comment]
Not sure what i can do here due to the way that Magic Items are added to the character sheets. I would have to get in contact with the author and work on a solution together.
