### ISSUE TITLE
opening a new ItemMacro closes existing ItemMacro editing window with no option to save

### ISSUE THREAD

**Issue by w15p** [Kekilla0/Item-Macro#63]
originally submitted to Improved Macro Editor, but it persists even with the stock foundry editor:
https://github.com/teroparvinen/foundry-improved-macro-editor/issues/5

I often want to reference multiple macros when developing and I forget that ItemMacro can only have one window open so I lose work because the window is replaced without a prompt to save.

Ideally support multiple windows, but at least don't close without prompting for a save

**Comment by krbz999** [comment]
I have a PR for this here #55.
