### ISSUE TITLE
Incompatible With Foundry V11

### ISSUE THREAD

**Issue by Grampasso96** [Kekilla0/Item-Macro#67]
The module is judged incompatible with version 11 of foundry, since it is a necessary dependency in many automatisms to manage macros, could it be made compatible with 11?

**Comment by arcanjl** [comment]
This is the last module I am waiting for before I can update to 11. It is a must-have for me. /plea

**Comment by YakFromStateFarm** [comment]
There seems to be a small error with `type` where it is set to 'Script' but should be all lowercase. This is the error that gets thrown when you try to run an ItemMacro, though it goes away if you hit save. I have a small local change that I could potentially make a PR for if enough people want it. Still testing it out to make sure it works the same way as in v10, but so far so good with a single code addition.

**Comment by Fridan99** [comment]
> There seems to be a small error with `type` where it is set to 'Script' but should be all lowercase. This is the error that gets thrown when you try to run an ItemMacro, though it goes away if you hit save. I have a small local change that I could potentially make a PR for if enough people want it. Still testing it out to make sure it works the same way as in v10, but so far so good with a single code addition.

Nice.....

**Comment by iansutherland75** [comment]
> There seems to be a small error with `type` where it is set to 'Script' but should be all lowercase. This is the error that gets thrown when you try to run an ItemMacro, though it goes away if you hit save. I have a small local change that I could potentially make a PR for if enough people want it. Still testing it out to make sure it works the same way as in v10, but so far so good with a single code addition.

Installed this to Forge via manifest and it's working.  I think the community preview would be well appreciated by people.

**Comment by dsakura** [comment]
> There seems to be a small error with `type` where it is set to 'Script' but should be all lowercase. This is the error that gets thrown when you try to run an ItemMacro, though it goes away if you hit save. I have a small local change that I could potentially make a PR for if enough people want it. Still testing it out to make sure it works the same way as in v10, but so far so good with a single code addition.

Yes please! (and thank you! lol)

**Comment by trioderegion** [comment]
https://github.com/Kekilla0/Item-Macro/releases/download/1.9.0%2B1/module.json
