### ISSUE TITLE
Magic Item Spell throwing error when trying to roll.

### ISSUE THREAD

**Issue by shirkie** [Kekilla0/Item-Macro#7]
When trying to use a spell from a magic item(using the "Magic Items" module), the following error gets thrown since dnd5e v 1.2.0 and in foundry v0.7.8.
![item-macro-error](https://user-images.githubusercontent.com/66429575/102270073-8a180a00-3eeb-11eb-8654-16756c62c1f2.png)
---
Edit 12/19/2020
It looks like this is only happening on 5e character sheets that are not the default sheet.  I've replicated it on both tidysheet and sky's alternative sheet.

**Comment by Kekilla0** [comment]
Not sure what i can do here due to the way that Magic Items are added to the character sheets. I would have to get in contact with the author and work on a solution together.
