### ISSUE TITLE
Manifest URL Not Found

### ISSUE THREAD

**Issue by kajishun** [Kekilla0/Item-Macro#71]
Works fine via Forge VTT on Foundry 10.291.
Manifest URL "Error: Unable to load valid module manifest data from... Module validation errors: packs: 0: type: may not be undefined via  Home Server on V11.305. Also does not show on Install Module screen.

**Comment by stevenagl12** [comment]
Is there any news to this?

**Comment by trioderegion** [comment]
https://github.com/Kekilla0/Item-Macro/releases/download/1.9.0%2B1/module.json
