### ISSUE TITLE
Item Macro not installing through manifest URL and not available through the add-on modules

### ISSUE THREAD

**Issue by stevenagl12** [Kekilla0/Item-Macro#72]
When I try to copy and paste the manifest URL directly from the readme file into foundry vtt it says Error: Unable to load valid module manifest data from "https://github.com/Kekilla0/Item-Macro/releases/download/v1.5.3/module.json" Module validation erros: packs: 0: type: may not be undefined

Furthermore, it is not available for the add-ons right now.

**Comment by JerryTheMac** [comment]
i installed it no problem through the releases link
https://github.com/Kekilla0/Item-Macro/releases/download/1.9.0%2B1/module.json

**Comment by franckflo** [comment]
That worked for me as well. Thanks!

**Comment by Nemodious** [comment]
+1 that link worked for me but I was having the same issue as OP - thank you!
