### ISSUE TITLE
Where is version 1.9.0?

### ISSUE THREAD

**Issue by Quinn-Aetherwood** [Kekilla0/Item-Macro#73]
I am using Midiqol and i am getting a warning saying i need 1.9.0. I don't see that version listed here.

**Comment by CapivaraTupiniquim** [comment]
https://github.com/Kekilla0/Item-Macro/releases/download/1.9.0+1/module.json

**Comment by Quinn-Aetherwood** [comment]
Thank you very much sir

**Comment by kaniplaynow** [comment]
> https://github.com/Kekilla0/Item-Macro/releases/download/1.9.0+1/module.json

Is this version older or newer than https://github.com/Kekilla0/Item-Macro/releases/download/1.9.0%2B1/module.json given in Issue #72?

I'm assuming that these manifest URLs aren't being pushed in the Bazaar because they are community-updated, is that right?

**Comment by kaniplaynow** [comment]
I'm curious why this doesn't show up in the Bazaar. It's still showing 1.8.0 as the latest version. I'm running v11 Patch 8 build 308

**Comment by trioderegion** [comment]
https://github.com/Kekilla0/Item-Macro/releases/download/1.9.0%2B1/module.json

It has not been released yet.
