### ISSUE TITLE
Problem with Tidy5E-Sheet

### ISSUE THREAD

**Issue by 9ryex5** [Kekilla0/Item-Macro#9]
When using [Tidy5E-Sheet](https://foundryvtt.com/packages/tidy5e-sheet/), Item Macro is triggering macros when using items from the Features tab. However when you add an item to favorites, Tidy5E shows them on the Attributes tab and Item Macro doesn't trigger when rolling the item from there.

**Comment by BlitzKraig** [comment]
Removing this codeblock seems to have fixed it for me.

https://github.com/Kekilla0/Item-Macro/blob/cb09fcdbb9c43ab19a65beb9ac965a598890bcbb/scripts/main.js#L93-L96

The previous hook call on line 83 already hooks into `renderTidySheet5e`, then is doubled to `renderedTidySheet5e`
https://github.com/Kekilla0/Item-Macro/blob/cb09fcdbb9c43ab19a65beb9ac965a598890bcbb/scripts/main.js#L83-L88

I'm not sure why Item Macro hooks the same function into both, but it appears to be causing the issue - though I can't say for sure that it won't break anything else.

If anyone else is able to try it out, let me know if it works fine and I can put up a PR

**Comment by Kekilla0** [comment]
This is probably a known issue seeing as i copied most of that code from midi-qol a lonnng time ago. I will fix it in the next version of the module.

**Comment by Haxxer** [comment]
Okay, so I looked into this a bit more - and it seems that the onus would be on Tidy5e-Sheet to include some hooks. It appears that the favorites are being created dynamically anytime the sheet is opened, and the hooks for those buttons are then created after Item Macro injected its hooks in the sheets' items. How best to solve this is beyond me, but I hope the extra information helps :)

**Comment by Kekilla0** [comment]
Found a work around, I know this is super late, lol. 
But better late than never!
